Update patch set 31
Patch Set 31:

> Patch Set 31:
> 
> Why did you bypass presubmit? The latest round of -1's definitely don't look like unrelated flaky tests:
> 
> out/soong/.intermediates/system/core/adb/libadbd_core/android_x86_64_static/obj/system/core/adb/daemon/auth.o system/core/adb/daemon/auth.cpp
> system/core/adb/daemon/auth.cpp:86:5: error: no matching function for call to 'adbd_auth_get_public_keys'
>     adbd_auth_get_public_keys(
>     ^~~~~~~~~~~~~~~~~~~~~~~~~
> frameworks/native/libs/adbd_auth/include/adbd_auth.h:90:6: note: candidate function not viable: no known conversion from '(lambda at system/core/adb/daemon/auth.cpp:88:13)' to 'bool (*)(void *, const char *, size_t)' (aka 'bool (*)(void *, const char *, unsigned long)') for 2nd argument
> void adbd_auth_get_public_keys(AdbdAuthContext* ctx,
>      ^
> system/core/adb/daemon/auth.cpp:165:8: error: no member named 'callbacks' in 'AdbdAuthCallbacks'
>     cb.callbacks.v1.key_authorized = adbd_auth_key_authorized;
>     ~~ ^
> 2 errors generated.

The issue was when I tried to submit the whole topic, it seemed to not work, so I ended up submitting the CLs one by one. When I did that, I found the system/core changes needed to be rebased. Gerrit should've warned me about that but didn't.

Patch-set: 31