Update patch set 1
Patch Set 1:

Where is android_flex_plane_t defined? As of 1pm PST this commit was causing a build breakage on my system due to the following error (and several more that followed).  I'm wondering if my repos have gotten out of sync somehow:

frameworks/native/libs/ui/GraphicBufferMapper.cpp:134:44: error: unknown type name 'android_flex_plane_t'; did you mean 'android_flex_layout'?
static inline bool isValidYCbCrPlane(const android_flex_plane_t& plane) {
                                           ^~~~~~~~~~~~~~~~~~~~
                                           android_flex_layout

Patch-set: 1